### ISSUE TITLE
Moving from ocamlp4 to PPX

### ISSUE THREAD

**Issue by xguerin** [ujamjar/hardcaml#12]
It would make the integration to tools like Merlin possible. Have you considered it ? If not, I can give it a shot. Starting with the `interface` and subscript `.[]` extensions should not be too difficult. Although that would imply a slight syntax change.

**Comment by andrewray** [comment]
I would definitely like to get rid of camlp4 and replace it with ppx.  I am not too sure how easily you can match the camlp4 syntax as we have to reuse ocaml syntax in ppx.

For interfaces I think the best solution would actually work like ppx_deriving - something like

```
module X = struct
  type 'a t = 
    {
      x : 'a [@bits 4];
      y : 'a [@bits n];
    } [@deriving interface]
end
```

Though perhaps something rather easier to port might look like

```
module%interface X = struct
  {| x[4] y[n] |}
end
```

For the `.[]` syntax we would need to reuse the 2d array access syntax I think.  This should only be done in qualified expressions ie

```
let x = [%hw y.[3,4]]
```

I did an experiment a while ago with this and also reinterpreted the standard ocaml operators so you could write things like

```
let x = [%hw (a.[3,4] + b) land c]
```

**Comment by andrewray** [comment]
Also, I think a really nice extension would generalise matching so you could define things like `option` as a hardware datatype, match over it, and the appropriate muxes would get inferred.

**Comment by xguerin** [comment]
For module I've been leaning toward the second solution. It's the easiest route since most of the existing logic could be reused.

For the `.[]` I reached the same conclusion. I've been fiddling with the syntax tree to find a nicer way than [%hw ...] to write it but without much success. [%hw ...] is not that bad though.

Inferring muxes with `match` is a great idea. I already have a bunch of code in `ppx_bitstring` that implements extended matching and adapting it would not be too much trouble.

**Comment by xguerin** [comment]
One more thing about `.[]`: we could generalize substitution by using a `let%hw` syntax. All subsequent operations could be inferred as HardCaml logic:

```ocaml
let%hw x = (a.[3,4] + b) land c
```

**Comment by xguerin** [comment]
I started to  [work on it](https://github.com/xguerin/ppx_hardcaml).

**Comment by andrewray** [comment]
Nice!

**Comment by xguerin** [comment]
After some investigation, I am gearing toward your initial comment about modules. I am tempted to use:

```ocaml
module X = struct
  type 'a t = 
    {
      x : 'a [@bits 4];
      y : 'a [@bits n];
    } [@deriving interface]
end
```

For one thing, and contrary to my initial thought, it looks like it will be simpler to implement. For another thing, it's more "ocamlish" as it relies on the actual OCaml AST.

**Comment by andrewray** [comment]
I would suggest the ppx deriving framework.  It already has map and I wrote
a map2 I can dig up.

Just need to_list (which could be done with map) and the t value.

It will also be a lot more general than the old interfaces which may be
useful for a match extension.

**Comment by xguerin** [comment]
Good idea, I'll look into it.

**Comment by andrewray** [comment]
Heres the map2 work I did https://github.com/andrewray/ppx_deriving/commits/map2

unfortunately mixed up with a couple of other things...

**Comment by xguerin** [comment]
You're most likely thinking ahead of me as I do not see an immediate use for that map2 plugin :)

On a side note, I believe both PPX rewriters are now feature complete, baring the likely rough edges. You can give them a shot by simply pinning the repos in `opam`. Barring any crippling issue, I'll release them in `opam`.

**Comment by andrewray** [comment]
I have added a number of issues, many of which are really enhancements.  The only issue I think really does need to be addressed is the ability to use arbitrary expressions in selects and interface bits/length specifications.

**Comment by xguerin** [comment]
Very nice. Thanks for the feedback.

**Comment by xguerin** [comment]
What about automatically naming signals defined within `let%hw` ?

```ocaml
let%hw some_sig = expr in ...
```

to become

```ocaml
let some_sig = ([%hw expr]) -- "some_sig" in ...
```

**Comment by andrewray** [comment]
The very first camlp5 syntax extension had something like this using a new `def` keyword

```
let a = 1 in
def b = x in (* let b = x -- "b" *)
def x[n] in (* let x = wire n *)
```

For some reason I never got it to work reliably in the camlp4 version.

The downside, I think, is you need to restrict it to left-hand-side binding patterns which you can (re)deconstruct ie

```
let%hw a,b,c = x 
```

would need transforming to

```
let a,b,c = 
  let a,b,c = x in (* extract sub-parts *)
  let a,b,c = a--"a",b--"b",c--"c" in (* name *)
  a,b,c
```

To be fair the `def` keyword did none of this and just assumed a single binding.

**Comment by xguerin** [comment]
> To be fair the def keyword did none of this and just assumed a single binding.

For my own sanity I could limit the support for automated signal naming to single bindings :)

**Comment by andrewray** [comment]
I think you might want a separate labelling mechanism, because the opposite example to the one I gave also exists

```
let%hw x = (a + b), (d land c)
```

Unless you want to restrict `let%hw` to the simplest forms (no tuples, lists etc on either side) which I think would be a shame.

**Comment by andrewray** [comment]
...but dont get me wrong - automatic naming was a very nice feature and I miss it especially for debugging simulations!

**Comment by xguerin** [comment]
It's not really necessary to restrict the full extension to get that to work. I could add a pass at the end of the rewriting pipeline that adds the signal naming operator only on a subset of supported operations that are likely to produce a signal: function calls, unary and binary operators, etc.

In the case of your example, `[%hw]` would still recursively rewrite the expression, but the naming stage would simply let the result pass through.

**Comment by andrewray** [comment]
This perhaps feeds back into the question of exactly what gets rewritten.  My view is that in

```
let%hw <pat> = <expr> in
```

the whole of <expr> is rewritten by replacing just the special constructs (ie select) and operators.  That lets us freely write let bindings, use tuples, lists, arrays for structuring stuff etc.

In this case I don't see how you can tell if `<expr>` can apply the `(--)` operator without type information.

If you are controlling the rewriting process more closely, then perhaps it is possible.

**Comment by xguerin** [comment]
I see. So no, the `let` statement is nor rewritten completely as a whole. The rewriter is designed to be recursive on expressions and only expressions matching a specific pattern are replaced. Others are passed through.

In the case of a `let` expression, it is matched with the following construct

    (value_binding, expression)

with `value_binding -> (ident, expression)`

In that case, the `PPX` extension rewrites the expression by wrapping the expression contained in the value bind with a `[%hw]` extension. As discussed previously, the choice of not wrapping the other expression is so deliberate as to keep the scope of the `[%hw]` extension under control.

> In this case I don't see how you can tell if <expr> can apply the (--) operator without type information.

I simply don't :) The same way I don't with the other replacement (`select`, binary operators, etc.). It is done optimistically. When an expression is matched to a list, a tuple, etc.. the `--` operator would not be applied. When it is matched to a value, or a function call, it would be optimistically applied.

The rationale being, since every let statement requires the `[%hw]` extension tag to be rewritten, modification can be applied piecemeal. For instance, let's say we have:

```ocaml
let func0 a b =
  [%hw a + b]

let func1 a b =
  let%hw c  = a + 2 in
  let%hw res = func0 b c in
  res
```
 
This would be properly supported and the signal resulting from `func0` would be properly named. However, let's say that you want to change the result type of `func0`:

```ocaml
let func0 a b =
  [%hw (a + b, a - b)]
```

Then `func1` would throw a compilation error because `--` cannot be applied to a tuple. In that case, you would need to redefine `func1` properly:

```
let func1 a b =
  let%hw c = a + 2 in
  let res = func0 b c in
  res
```

I hope that clarifies a bit :)
