### ISSUE TITLE
$== precedence over |: operator

### ISSUE THREAD

**Issue by xguerin** [ujamjar/hardcaml#17]
I've noticed that `$==` seems to take precedence over `|:`:

```ocaml
some_sig $== a |:b;
```

Requires `(a |: b)` to work. According to the OCaml precedence rules that sort of makes sense as both `$` and `|` have the same priority.

Maybe it would make sense to use `<-:` instead ?

**Comment by andrewray** [comment]
Yes, that's true and it's caught me out endless times!

I will add a depreciation warning on `$==` and add your suggestion.
