### ISSUE TITLE
Cannot use HardCaml.Syntax

### ISSUE THREAD

**Issue by Jhana1** [ujamjar/hardcaml#6]
It's highly likely that I'm doing something wrong, but I am unable to use the HardCaml.Syntax extension, as shown in the following screenshot.
![image](https://cloud.githubusercontent.com/assets/9104199/12280755/7b81a30c-b9e4-11e5-9ff5-635d170c4d87.png)

Because of this I am also unable to follow the tutorial here (http://www.ujamjar.com/hardcaml/simulation.html).

Thanks in Advance.

**Comment by andrewray** [comment]
Start utop then enable camlp4 and load hardcaml with the syntax extension

```
$ utop
utop> #camlp4o;;
utop> #require "hardcaml.syntax";;
utop> open HardCaml.Bits.Comb.IntbitsList;;
utop> (consthu 8 "0a").[7:4];;
- : t = [0; 0; 0; 0]    
```

**Comment by Jhana1** [comment]
Thankyou, Working perfectly!

**Comment by andrewray** [comment]
No problem.  While I'm here I should point out there is a small difference in the simulation tutorial code and the latest HardCaml release (the tutorial is built based on the previous release - I really should get this updated...);

```
let circ,sim,i,o = Builder.make "up_down_counter" up_down_counter_if
```

An extra value is returned here so you need

```
let circ,sim,i,o,_ = Builder.make "up_down_counter" up_down_counter_if
```

**Comment by Jhana1** [comment]
Thanks Again, just ran into that issue.

**Comment by andrewray** [comment]
I have just updated the website to fix this inconsistency with the latest hardcaml version.

**Comment by philtomson** [comment]
I ran into the same issue with the select syntax extension Jhana1 reported above, however, when I try the following fix as suggested above, I get:

```
    $ utop
    utop> #camlp4o;;
    utop was built without camlp4 support.
```

This is with utop 2.0.1 and OCaml 4.05.0.

**Comment by andrewray** [comment]
I'd strongly recommend looking into the newer ppx infrastructure

https://github.com/xguerin/ppx_hardcaml
https://github.com/xguerin/ppx_deriving_hardcaml
