### ISSUE TITLE
Tracing internal signals

### ISSUE THREAD

**Issue by xguerin** [ujamjar/hardcaml#8]
Hello,

Is there a way to get the VCD wrapper to generate also internal signals, and not just Input/Output signals ? I looked at the code of the wrapper, and it seems that it is already scanning for internal signals. However, I don't seem to get them added in my VCD.

Thanks,

**Comment by andrewray** [comment]
There is an optional "internal" arg to the simulator make function.

Return true for signals you want to trace.  I generally check if the signal
has a name ie

```
fun s -> names s <> []
```

**Comment by xguerin** [comment]
Sweet, thanks !
