### ISSUE TITLE
Complex top level example

### ISSUE THREAD

**Issue by xguerin** [ujamjar/hardcaml#9]
Is there by any chance an example of a HardCaml top level that combines multiple HardCaml components altogether ? I am especially curious to know how "interfaces" can be exported given that the "interface" extension does not work in an `.mli` AFAICT.

**Comment by andrewray** [comment]
You can have a look here https://github.com/ujamjar/hardcaml-reedsolomon/blob/master/src/codec.mli

Interfaces do work as signatures, but with a slightly different syntax ie

```
module S : interface
  a b{ } c{| |}
end = interface
 a[2] b{3}[7] c{|6|}[1]
end
```

(a is a 2 bit signal, b is a list of 3 7 bit signals and c is an array of 6 1 bit signals)

you basically just drop the bit specification off the end and don't specify the array/list size.

**Comment by xguerin** [comment]
Thanks for the pointer. That's pretty cool. The very idea of finally being able to unit test my designs makes me giddy like a schoolgirl.
